### ISSUE TITLE
Migracija iz "spletnega praskanja" na preprost API za eAsistent prijavo

### ISSUE THREAD

**Issue by mytja** [JurijTSL/JEA#4]
Pozdravljen,
prvo kot prvo, ker ne vem, kako se vi tukaj pogovarjate na vaših repozitorijih, bom govoril kar po slovensko.

<details>
  <summary>Neumesno sporočilo glede OpenTimetable formata</summary>

  V glavnem, sem ustvarjalec [MeetPlan sistema](https://github.com/MeetPlan), kot si verjetno že lahko videl. Čeprav je to neumesno, sem te nekako želel kontaktirati glede [OpenTimetable formata](https://github.com/OpenTimetable) in ti povedati, da mi je zelo všeč in podpiram te napore k standardizaciji urnika, posledično bom tudi implementiral OpenTimetable format, ko bom dopolnil manjkajoče stvari v svoji podatkovni bazi. OpenTimetable format ima zagotovo velike potenciale, predvsem na importanju, exportanju urnikov, kot tudi potencialno machine learninga z zbiranjem urnikov, tako da vse čestitke za vajin trud. Zdaj pa dovolj tega obupnega oglaševanja in prehod k glavni stvari.
</details>

eAsistent nam ni naredil lepega API-ja za prijavo, če pogledamo na spletni aplikaciji, ampak če pogledamo na mobilno aplikacijo, lahko vidimo, da imamo zelo preprost API za prijavo, zato bi bilo pametno nadomestiti to spletno praskanje, ki ga trenutno izvajaš tukaj

https://github.com/chocoearly44/JEA/blob/d39a1cd7f5bbda0b65d0639ac5237ce1caec6007/src/main/java/tk/thesuperlab/jea/JEA.java#L164-L202

z nečem bolj takšnim (to je Python skripta - za uporabo je treba namestiti "requests" knjižico):
```py
import requests

username = "mojeuporabniskoime"
password = "mojezelovarnogeslo"

# Tole se bo samo enkodiralo v JSON format preko `json` argumenta v `requests.post` funkciji.
# Enkodirano se pošlje enako, kot navaden POST request body.
json = {
    'username': username,
    'password': password,
    'supported_user_types': ['child'],
}

headers = {
    'Content-Type': 'application/json',
    'x-app-name': 'family',
    'x-client-version': '13',
    'x-client-platform': 'web',
};

r = requests.post("https://www.easistent.com/m/login", json=json, headers=headers)

print(r.json())

```

Mislim, da zgornji primer zelo dobro ponazori, kaj je treba poslati (tudi če ne poznaš Pythona). Nisem "Java" strokovnjak (oz. sploh ne znam Jave). Če bi jo, bi zagotovo contributal temu projektu prek PR-a.

Pomembno je vedeti, da taka prijava pošlje elektronsko sporočilo na uporabnikov elektronski naslov.

Lep pozdrav

**Comment by chocoearly44** [comment]
Sem naredil par testov in dejansko je bearer token enak tistemu pri AJAX prijavi. Bom posodobil prijavo v naslednji verziji, hvala.

**Comment by chocoearly44** [comment]
Kar pa se tiče OTTF-ja, sem vesel, da se zanimaš zanj. Kontaktiraš pa me lahko načeloma na vseh [teh platformah](https://github.com/chocoearly44#social).
